// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzuocuhthbuyeiwtjmvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6dW9jdWh0aGJ1eWVpd3RqbXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyODM1OTUsImV4cCI6MjA4ODg1OTU5NX0.qv0aMohFI2K6JwFtrK91Yf_UryHFXR2xeSMIBe4d81o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});